# Generated by Django 5.0.6 on 2024-05-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShippingAdress",
            new_name="ShippingAddress",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="Digital",
            new_name="exist",
        ),
    ]
