# Generated by Django 5.0.6 on 2024-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_shippingadress_shippingaddress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default=False,
                height_field=360,
                null=True,
                upload_to="",
                width_field=640,
            ),
        ),
    ]
