# Generated by Django 5.0.6 on 2024-05-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_height_field_product_width_field_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="height_field",
        ),
        migrations.RemoveField(
            model_name="product",
            name="width_field",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, default=False, null=True, upload_to=""),
        ),
    ]
