# Generated by Django 5.0.6 on 2024-05-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_remove_product_height_field_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
