# Generated by Django 5.0.6 on 2024-05-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_remove_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, default=False, null=True, upload_to=""),
        ),
    ]
