# Generated by Django 5.0.6 on 2024-05-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default=False, null=True, upload_to="static/img"
            ),
        ),
    ]
