# Generated by Django 5.0.6 on 2024-05-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, default=False, null=True, upload_to=""),
        ),
    ]
