# Generated by Django 5.0.6 on 2024-05-24 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="Order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="store.order",
            ),
        ),
    ]
