# Generated by Django 5.0.6 on 2024-05-25 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_orderitems_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitems",
            old_name="Order",
            new_name="order_id",
        ),
    ]
