# Generated by Django 5.0.6 on 2024-05-25 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_rename_order_orderitems_order_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitems",
            old_name="order_id",
            new_name="Order",
        ),
    ]
