# Generated by Django 5.0.6 on 2024-05-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_rename_order_id_orderitems_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
